# Generated by Django 5.1.7 on 2025-04-13 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0004_alter_plat_is_available'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='plat',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='platingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='platingredient',
            name='plat',
        ),
        migrations.AlterField(
            model_name='commandeplat',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.plat'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='plats',
            field=models.ManyToManyField(through='restaurant.CommandePlat', to='SuperAdmin.plat'),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='PlatIngredient',
        ),
        migrations.DeleteModel(
            name='Plat',
        ),
    ]
