# Generated by Django 5.1.7 on 2025-04-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_delete_restaurant_commande_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='statut_preparation',
        ),
    ]
