# Generated by Django 5.2 on 2025-04-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_evaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='adresse',
        ),
    ]
