# Generated by Django 5.2 on 2025-04-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_rename_address_client_adresse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='telephone',
        ),
    ]
