# Generated by Django 5.2 on 2025-05-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_livreur_livraison'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livraison',
            options={'verbose_name': 'Livraison', 'verbose_name_plural': 'Livraisons'},
        ),
        migrations.AlterModelOptions(
            name='livreur',
            options={'verbose_name': 'Livreur', 'verbose_name_plural': 'Livreurs'},
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='date_livraison',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='id',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='livreur',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='id',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='statut_disponibilite',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='telephone',
        ),
        migrations.AddField(
            model_name='livraison',
            name='id_cmd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='restaurant.commande', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='id_liv',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='livraison',
            name='id_livr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='restaurant.livreur', verbose_name='Livreur'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='id_livr',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='livreur',
            name='statut_dispo',
            field=models.BooleanField(choices=[(True, 'Disponible'), (False, 'Indisponible')], default=True, verbose_name='Statut de disponibilité'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='adresse',
            field=models.CharField(max_length=255, verbose_name='Adresse de livraison'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date',
            field=models.DateTimeField(verbose_name='Date de livraison'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='etat_livraison',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('retour', 'Retour'), ('probleme', 'Problème')], default='en_attente', max_length=20, verbose_name='État de la livraison'),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='nom_livr',
            field=models.CharField(max_length=100, verbose_name='Nom du livreur'),
        ),
    ]
