# Generated by Django 5.2 on 2025-05-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_reservation_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('cash', 'Paiement à la livraison'), ('carte', 'Carte bancaire'), ('sur_place', 'Sur place')], default='cash', max_length=20),
        ),
    ]
