# Generated by Django 5.1.6 on 2025-04-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_alter_historiqueplat_unique_together'),
        ('SuperAdmin', '0010_remove_restaurant_admin_admin_restaurant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historiqueingredient',
            unique_together={('ingredient', 'date', 'restaurant')},
        ),
    ]
