# Generated by Django 5.1.6 on 2025-04-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0002_plat_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
