# Generated by Django 5.1.7 on 2025-04-18 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0004_alter_plat_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantite', models.IntegerField(default=0)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.plat')),
            ],
            options={
                'unique_together': {('date', 'plat')},
            },
        ),
        migrations.CreateModel(
            name='UtilisationIngredientJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantite_utilisee', models.FloatField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.ingredient')),
            ],
            options={
                'unique_together': {('date', 'ingredient')},
            },
        ),
    ]
