# Generated by Django 5.1.6 on 2025-04-25 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0006_restaurant_admin_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='admin_local',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='SuperAdmin.admin'),
        ),
    ]
