# Generated by Django 5.1.6 on 2025-04-25 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0007_remove_restaurant_admin_local_restaurant_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='SuperAdmin.restaurant'),
        ),
        migrations.AddField(
            model_name='plat',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.restaurant'),
        ),
    ]
