# Generated by Django 5.1.6 on 2025-04-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0008_categorie_restaurant_plat_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='nom',
            new_name='name',
        ),
    ]
