# Generated by Django 5.2 on 2025-04-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0009_rename_nom_categorie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='restaurant',
        ),
    ]
