# Generated by Django 5.1.6 on 2025-04-30 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0010_remove_restaurant_admin_admin_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('date', models.DateField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.ingredient')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.restaurant')),
            ],
            options={
                'unique_together': {('ingredient', 'date', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='HistoriquePlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.plat')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.restaurant')),
            ],
            options={
                'unique_together': {('plat', 'date', 'restaurant')},
            },
        ),
    ]
