# Generated by Django 5.2 on 2025-05-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0010_remove_plat_restaurant'),
        ('SuperAdmin', '0011_historiqueingredient_historiqueplat'),
    ]

    operations = [
    ]
