# Generated by Django 5.1.6 on 2025-05-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0011_historiqueingredient_historiqueplat'),
        ('SuperAdmin', '0013_plat_etape'),
    ]

    operations = [
    ]
