# Generated by Django 5.1.6 on 2025-04-28 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0010_remove_restaurant_admin_admin_restaurant'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.restaurant'),
        ),
    ]
