# Generated by Django 5.1.6 on 2025-04-28 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0010_remove_restaurant_admin_admin_restaurant'),
        ('home', '0002_offre_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SuperAdmin.admin'),
        ),
    ]
