# Generated by Django 5.1.6 on 2025-04-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0010_remove_restaurant_admin_admin_restaurant'),
        ('home', '0003_customuser_admin_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.restaurant'),
        ),
    ]
