# Generated by Django 5.1.7 on 2025-04-14 22:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_plat_categorie_remove_plat_ingredients_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.AddField(
            model_name='commande',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut_preparation',
            field=models.CharField(choices=[('En cours de préparation', 'En cours de préparation'), ('Prête', 'Prête')], default='En cours de préparation', max_length=25),
        ),
    ]
