# Generated by Django 5.1.7 on 2025-04-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_commande_statut_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de préparation'), ('En cours de préparation', 'En cours de préparation'), ('livree', 'Livrée'), ('annulee', 'Annulée'), ('Prête', 'Prête')], default='en_attente', max_length=25),
        ),
    ]
