# Generated by Django 5.1.6 on 2025-04-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_commande_statut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offre',
        ),
    ]
