# Generated by Django 5.2 on 2025-04-30 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_livr', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('statut_disponibilite', models.CharField(choices=[('Disponible', 'Disponible'), ('En livraison', 'En livraison'), ('Indisponible', 'Indisponible')], default='Disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_livraison', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente', max_length=20)),
                ('adresse', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='restaurant.commande')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='restaurant.livreur')),
            ],
        ),
    ]
