# Generated by Django 5.2 on 2025-05-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_table_restaurant'),
        ('restaurant', '0010_client_user'),
    ]

    operations = [
    ]
