# Generated by Django 5.2 on 2025-05-01 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_livreur_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livraison',
            options={},
        ),
        migrations.AlterModelOptions(
            name='livreur',
            options={},
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='id_liv',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='user',
        ),
        migrations.AddField(
            model_name='livraison',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='statut_disponibilité',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='etat_livraison',
            field=models.CharField(choices=[('attente', 'En attente'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée'), ('probleme', 'Problème')], default='attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='id_cmd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.commande'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='id_livr',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='restaurant.livreur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livreur',
            name='nom_livr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='statut_dispo',
            field=models.BooleanField(default=True),
        ),
    ]
