# Generated by Django 5.2 on 2025-05-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_table_restaurant'),
        ('restaurant', '0011_alter_livraison_options_alter_livreur_options_and_more'),
    ]

    operations = [
    ]
