# Generated by Django 5.2 on 2025-05-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0012_merge_20250501_1201'),
        ('restaurant', '0013_alter_reservation_client_alter_commande_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.restaurant'),
        ),
    ]
