# Generated by Django 5.2 on 2025-05-01 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0012_merge_20250501_1201'),
        ('restaurant', '0014_alter_commande_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.restaurant'),
        ),
    ]
