# Generated by Django 5.1.6 on 2025-04-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
