# Generated by Django 5.1.6 on 2025-04-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0003_plat_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
