# Generated by Django 5.1.6 on 2025-04-28 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0009_rename_nom_categorie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='admin',
        ),
        migrations.AddField(
            model_name='admin',
            name='restaurant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.restaurant'),
            preserve_default=False,
        ),
    ]
