# Generated by Django 5.2 on 2025-04-29 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0010_remove_restaurant_admin_admin_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Code Postal')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text="Latitude de l'adresse (sera remplie par la carte)", max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text="Longitude de l'adresse (sera remplie par la carte)", max_digits=9, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='plat',
            name='restaurant',
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('livraison_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Livraison')),
                ('date_de_livraison', models.DateTimeField(blank=True, help_text="La date et l'heure réelles de la livraison", null=True, verbose_name='Date de Livraison')),
                ('date_de_livraison_estimée', models.DateTimeField(blank=True, help_text="La date et l'heure estimées de la livraison", null=True, verbose_name='Date de Livraison Estimée')),
                ('transporteur', models.CharField(blank=True, help_text='Nom du transporteur', max_length=100, verbose_name='Transporteur')),
                ('numéro_de_suivi', models.CharField(blank=True, help_text="Numéro de suivi de l'expédition", max_length=150, verbose_name='Numéro de Suivi')),
                ('statut', models.CharField(choices=[('en_attente', 'En Attente'), ('en_cours_de_traitement', 'En Cours de Traitement'), ('expédié', 'Expédié'), ('livré', 'Livré'), ('annulé', 'Annulé'), ('retourné', 'Retourné')], db_index=True, default='en_attente', help_text='Le statut actuel de la livraison', max_length=25, verbose_name='Statut de la Livraison')),
                ('notes', models.TextField(blank=True, help_text='Toutes instructions ou notes spéciales relatives à la livraison', null=True, verbose_name='Notes de Livraison')),
                ('date_de_création', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('date_de_mise_à_jour', models.DateTimeField(auto_now=True, verbose_name='Date de Mise à Jour')),
                ('disponibilite', models.BooleanField(default=True, help_text='Is the delivery person available?', verbose_name='Disponibilité')),
                ('adresse_de_livraison', models.ForeignKey(help_text="L'adresse où la commande doit être livrée", on_delete=django.db.models.deletion.CASCADE, related_name='livraisons_a', to='SuperAdmin.adresse', verbose_name='Adresse de Livraison')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_de_création'],
            },
        ),
    ]
