# Generated by Django 5.2 on 2025-04-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0011_adresse_remove_categorie_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='adresse_de_livraison',
        ),
        migrations.DeleteModel(
            name='Adresse',
        ),
        migrations.DeleteModel(
            name='Livraison',
        ),
    ]
