# Generated by Django 5.2 on 2025-05-02 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0012_merge_20250501_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plats', to='SuperAdmin.categorie'),
        ),
    ]
