# Generated by Django 5.2 on 2025-05-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0012_remove_livraison_adresse_de_livraison_delete_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='etape',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
