# Generated by Django 5.2 on 2025-04-27 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SuperAdmin', '0009_rename_nom_categorie_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('date', models.DateField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.ingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HistoriquePlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.plat')),
            ],
            options={
                'unique_together': {('plat', 'date')},
            },
        ),
    ]
