# Generated by Django 5.1.6 on 2025-04-28 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_delete_depense'),
        ('SuperAdmin', '0010_remove_restaurant_admin_admin_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueingredient',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.restaurant'),
        ),
        migrations.AddField(
            model_name='historiqueplat',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.restaurant'),
        ),
    ]
