# Generated by Django 5.1.6 on 2025-04-28 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_historiqueingredient_restaurant_and_more'),
        ('SuperAdmin', '0010_remove_restaurant_admin_admin_restaurant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historiqueplat',
            unique_together={('plat', 'date', 'restaurant')},
        ),
    ]
