# Generated by Django 5.1.6 on 2025-04-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_depense'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historiqueplat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='historiqueplat',
            name='plat',
        ),
        migrations.RemoveField(
            model_name='historiqueplat',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='HistoriqueIngredient',
        ),
        migrations.DeleteModel(
            name='HistoriquePlat',
        ),
    ]
